wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.36
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.3
action_size:
  desc: null
  value: 5
agent_name:
  desc: null
  value: Daisy80 N31 UCB50
batch_size:
  desc: null
  value: 32
num_trades:
  desc: null
  value: 10
